#!/bin/bash

echo "🔧 Setup GitHub Integration untuk Jenkins - Updated Version"
echo "=========================================================="
echo ""

# Konfigurasi GitHub credentials
GITHUB_USERNAME="abudlfalaq5@gmail.com"
GITHUB_TOKEN="[MASUKKAN_GITHUB_TOKEN_DI_SINI]"

echo "📋 Informasi Jenkins:"
echo "🌐 Jenkins UI: https://bangjeje.motorsights.com"
echo "👤 GitHub Username: $GITHUB_USERNAME"
echo "🔑 GitHub Token: $GITHUB_TOKEN"
echo ""

echo "📝 Langkah-langkah setup GitHub integration:"
echo ""

echo "1️⃣ Buka Jenkins UI di browser:"
echo "   https://bangjeje.motorsights.com"
echo ""

echo "2️⃣ Install GitHub Plugins (Plugin yang BENAR-BENAR ada):"
echo "   - Manage Jenkins → Manage Plugins"
echo "   - Tab 'Available' → cari dan install:"
echo ""
echo "   🔹 Plugin Utama:"
echo "     • GitHub Plugin (plugin utama untuk GitHub integration)"
echo "     • Git Plugin (untuk Git operations)"
echo ""
echo "   🔹 Plugin Tambahan (opsional tapi recommended):"
echo "     • GitHub Branch Source Plugin"
echo "     • GitHub Authentication Plugin"
echo "     • Pipeline: GitHub Plugin"
echo ""
echo "   ⚠️  JANGAN INSTALL: GitHub Pull Request Builder (ada vulnerability)"
echo ""
echo "   📝 Catatan Penting:"
echo "     - GitHub API Plugin biasanya sudah terinstall otomatis"
echo "     - Jika plugin tidak ditemukan, coba cari dengan nama yang berbeda"
echo "     - Restart Jenkins setelah install plugin"
echo ""

echo "3️⃣ Setup GitHub Credentials:"
echo "   - Manage Jenkins → Manage Credentials"
echo "   - System → Global credentials → Add Credentials"
echo "   - Kind: 'Secret text'"
echo "   - Secret: $GITHUB_TOKEN"
echo "   - ID: github-token"
echo "   - Description: GitHub Personal Access Token"
echo ""

echo "4️⃣ Konfigurasi GitHub Server:"
echo "   - Manage Jenkins → Configure System"
echo "   - Scroll ke bagian 'GitHub'"
echo "   - Add GitHub Server:"
echo "     • Name: GitHub"
echo "     • API URL: https://api.github.com"
echo "     • Credentials: github-token"
echo "     • Test connection (harus berhasil)"
echo ""

echo "5️⃣ Setup Webhook (untuk auto-trigger):"
echo "   - Di repository GitHub: Settings → Webhooks → Add webhook"
echo "   - Payload URL: https://bangjeje.motorsights.com/github-webhook/"
echo "   - Content type: application/json"
echo "   - Events: Just the push event"
echo "   - Active: ✓ (centang)"
echo ""

echo "6️⃣ Test GitHub Integration:"
echo "   - Buat Multibranch Pipeline:"
echo "     • New Item → Multibranch Pipeline"
echo "     • Branch Sources: GitHub"
echo "     • Credentials: github-token"
echo "     • Owner: [GitHub username atau organization]"
echo "     • Repository: [Repository name]"
echo "     • Save"
echo ""

echo "🔍 Troubleshooting Plugin GitHub:"
echo ""
echo "❌ Jika plugin tidak ditemukan:"
echo "   - Cek nama plugin yang benar di https://plugins.jenkins.io/"
echo "   - Pastikan Jenkins versi terbaru"
echo "   - Restart Jenkins setelah install plugin"
echo ""
echo "❌ Jika GitHub connection gagal:"
echo "   - Pastikan token memiliki permission yang benar"
echo "   - Cek expiry date token"
echo "   - Test connection di Configure System"
echo ""
echo "❌ Jika webhook tidak berfungsi:"
echo "   - Pastikan URL webhook benar"
echo "   - Cek firewall settings"
echo "   - Pastikan Jenkins bisa diakses dari internet"
echo ""

echo "📚 Plugin GitHub yang Tersedia (2024):"
echo ""
echo "✅ Plugin Utama:"
echo "   - GitHub Plugin (github-plugin)"
echo "   - Git Plugin (git-plugin)"
echo ""
echo "✅ Plugin Tambahan (AMAN):"
echo "   - GitHub Branch Source Plugin (github-branch-source)"
echo "   - GitHub Authentication Plugin (github-oauth)"
echo "   - Pipeline: GitHub Plugin (pipeline-github)"
echo "   - GitHub Organization Folder Plugin (github-organization-folder)"
echo ""
echo "❌ Plugin yang TIDAK AMAN (JANGAN INSTALL):"
echo "   - GitHub Pull Request Builder (ghprb) - ADA VULNERABILITY"
echo ""

echo "✅ Setup selesai! Jenkins siap untuk GitHub integration."
echo ""
echo "🧪 Test dengan membuat Multibranch Pipeline:"
echo "   - New Item → Multibranch Pipeline"
echo "   - Branch Sources: GitHub"
echo "   - Credentials: github-token"
echo "   - Owner: [GitHub username]"
echo "   - Repository: [Repository name]"
echo ""
echo "🌐 Akses Jenkins: https://bangjeje.motorsights.com"
