#!/bin/bash

echo "🔧 Setup GitHub Credentials untuk Jenkins..."

# Konfigurasi GitHub credentials
GITHUB_USERNAME="abudlfalaq5@gmail.com"
GITHUB_TOKEN="[MASUKKAN_GITHUB_TOKEN_DI_SINI]"

echo "📋 Informasi Jenkins:"
echo "🌐 Jenkins UI: http://localhost:9533"
echo "👤 GitHub Username: $GITHUB_USERNAME"
echo "🔑 GitHub Token: $GITHUB_TOKEN"
echo ""

echo "📝 Langkah-langkah setup GitHub integration:"
echo ""
echo "1️⃣ Buka Jenkins UI di browser:"
echo "   http://localhost:9533"
echo ""
echo "2️⃣ Install GitHub Plugins:"
echo "   - Manage Jenkins → Manage Plugins"
echo "   - Tab 'Available' → cari dan install:"
echo "     • GitHub Plugin (plugin utama)"
echo "     • GitHub Branch Source Plugin"
echo "     • GitHub Authentication Plugin"
echo "     • Pipeline: GitHub Plugin"
echo "     • Git Plugin (jika belum ada)"
echo ""
echo "   📝 Catatan: GitHub API Plugin biasanya sudah terinstall otomatis"
echo "   sebagai dependensi dari GitHub Plugin."
echo ""
echo "3️⃣ Setup GitHub Credentials:"
echo "   - Manage Jenkins → Manage Credentials"
echo "   - System → Global credentials → Add Credentials"
echo "   - Kind: 'Secret text'"
echo "   - Secret: $GITHUB_TOKEN"
echo "   - ID: github-token"
echo "   - Description: GitHub Personal Access Token"
echo ""
echo "4️⃣ Konfigurasi GitHub Server:"
echo "   - Manage Jenkins → Configure System"
echo "   - Scroll ke bagian 'GitHub'"
echo "   - Add GitHub Server:"
echo "     • Name: GitHub"
echo "     • API URL: https://api.github.com"
echo "     • Credentials: github-token"
echo "     • Test connection"
echo ""
echo "5️⃣ Setup Webhook (untuk auto-trigger):"
echo "   - Di repository GitHub: Settings → Webhooks → Add webhook"
echo "   - Payload URL: http://[JENKINS_SERVER]:9533/github-webhook/"
echo "   - Content type: application/json"
echo "   - Events: Just the push event"
echo ""
echo "✅ Setup selesai! Jenkins siap untuk GitHub integration."
echo ""
echo "🧪 Test dengan membuat Multibranch Pipeline:"
echo "   - New Item → Multibranch Pipeline"
echo "   - Branch Sources: GitHub"
echo "   - Credentials: github-token"
echo "   - Owner: [GitHub username]"
echo "   - Repository: [Repository name]"
