#!/bin/bash

echo "🔒 Setup Jenkins Multibranch Pipeline (AMAN) - Pengganti GitHub Pull Request Builder"
echo "=================================================================================="
echo ""

echo "⚠️  MENGAPA MULTIBRANCH PIPELINE LEBIH AMAN:"
echo "   - Tidak ada vulnerability seperti GitHub Pull Request Builder"
echo "   - Official Jenkins plugin yang ter-maintain"
echo "   - Lebih modern dan powerful"
echo "   - Built-in security features"
echo ""

echo "📋 PRASYARAT:"
echo "   ✅ GitHub Plugin sudah terinstall"
echo "   ✅ Git Plugin sudah terinstall"
echo "   ✅ GitHub Branch Source Plugin sudah terinstall"
echo "   ✅ GitHub credentials sudah dikonfigurasi"
echo ""

echo "🚀 LANGKAH SETUP MULTIBRANCH PIPELINE:"
echo ""

echo "1️⃣ BUAT MULTIBRANCH PIPELINE:"
echo "   - Buka Jenkins UI: https://bangjeje.motorsights.com"
echo "   - New Item → Multibranch Pipeline"
echo "   - Name: [nama-project]"
echo "   - OK"
echo ""

echo "2️⃣ KONFIGURASI BRANCH SOURCES:"
echo "   - Branch Sources: GitHub"
echo "   - Credentials: github-token"
echo "   - Owner: [GitHub username atau organization]"
echo "   - Repository: [nama repository]"
echo ""

echo "3️⃣ KONFIGURASI BUILD STRATEGIES:"
echo "   - Discover branches: ✓"
echo "   - Discover pull requests from origin: ✓"
echo "   - Discover pull requests from forks: ✓ (opsional)"
echo "   - Discover tags: ✓ (opsional)"
echo ""

echo "4️⃣ KONFIGURASI ADVANCED:"
echo "   - Build strategies:"
echo "     • Build PRs: ✓"
echo "     • Build branches: ✓"
echo "   - Orphaned item strategy:"
echo "     • Discard old items: ✓"
echo "     • Days to keep: 7"
echo "     • Max # of builds to keep: 10"
echo ""

echo "5️⃣ SETUP JENKINSFILE:"
echo "   - Buat file Jenkinsfile di root repository:"
echo ""
echo "   ```groovy"
echo "   pipeline {"
echo "       agent any"
echo "       "
echo "       stages {"
echo "           stage('Checkout') {"
echo "               steps {"
echo "                   checkout scm"
echo "               }"
echo "           }"
echo "           "
echo "           stage('Build') {"
echo "               steps {"
echo "                   echo 'Building application...'"
echo "                   // Tambahkan command build sesuai project"
echo "               }"
echo "           }"
echo "           "
echo "           stage('Test') {"
echo "               steps {"
echo "                   echo 'Running tests...'"
echo "                   // Tambahkan command test"
echo "               }"
echo "           }"
echo "       }"
echo "       "
echo "       post {"
echo "           always {"
echo "               echo 'Pipeline completed!'"
echo "           }"
echo "       }"
echo "   }"
echo "   ```"
echo ""

echo "6️⃣ SETUP WEBHOOK (untuk auto-trigger):"
echo "   - Di repository GitHub: Settings → Webhooks → Add webhook"
echo "   - Payload URL: https://bangjeje.motorsights.com/github-webhook/"
echo "   - Content type: application/json"
echo "   - Events: Just the push event"
echo "   - Active: ✓"
echo ""

echo "7️⃣ TEST PIPELINE:"
echo "   - Scan repository: Scan Multibranch Pipeline Now"
echo "   - Cek apakah branches dan PRs terdeteksi"
echo "   - Test build dengan push ke branch atau buat PR"
echo ""

echo "🔒 KEAMANAN MULTIBRANCH PIPELINE:"
echo ""
echo "✅ Built-in Security Features:"
echo "   - CSRF protection enabled by default"
echo "   - Proper permission checks"
echo "   - No credential enumeration vulnerability"
echo "   - Regular security updates"
echo ""
echo "✅ Best Practices:"
echo "   - Use least privilege principle"
echo "   - Regular plugin updates"
echo "   - Monitor security advisories"
echo "   - Use official plugins only"
echo ""

echo "🔍 TROUBLESHOOTING:"
echo ""
echo "❌ Jika branches tidak terdeteksi:"
echo "   - Cek credentials GitHub"
echo "   - Pastikan repository accessible"
echo "   - Test connection di Configure System"
echo ""
echo "❌ Jika webhook tidak berfungsi:"
echo "   - Cek URL webhook"
echo "   - Pastikan Jenkins accessible dari internet"
echo "   - Cek firewall settings"
echo ""
echo "❌ Jika build gagal:"
echo "   - Cek Jenkinsfile syntax"
echo "   - Pastikan tools yang diperlukan terinstall"
echo "   - Review build logs"
echo ""

echo "📚 KEUNTUNGAN MULTIBRANCH PIPELINE:"
echo ""
echo "✅ Dibandingkan GitHub Pull Request Builder:"
echo "   - Lebih aman (no vulnerabilities)"
echo "   - Lebih powerful dan flexible"
echo "   - Built-in branch management"
echo "   - Better integration dengan GitHub"
echo "   - Modern Jenkins best practices"
echo ""

echo "✅ Fitur yang Tersedia:"
echo "   - Automatic branch discovery"
echo "   - PR builds otomatis"
echo "   - Tag builds"
echo "   - Orphaned item cleanup"
echo "   - Build strategies customization"
echo ""

echo "🎯 LANGKAH SELANJUTNYA:"
echo ""
echo "1. UNINSTALL GitHub Pull Request Builder plugin"
echo "2. SETUP Multibranch Pipeline sesuai panduan di atas"
echo "3. TEST pipeline dengan push/PR"
echo "4. MONITOR security updates secara berkala"
echo ""

echo "✅ Multibranch Pipeline siap digunakan!"
echo ""
echo "🌐 Akses Jenkins: https://bangjeje.motorsights.com"
